// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Keep client generation working in clean CI/Vercel environments
    // even when DATABASE_URL is not injected at install time.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
